### ISSUE TITLE
百度地图的jar都丢失了？

### ISSUE THREAD

**Issue by s1168805219** [Sambor123/foodie-app#2]
真是怎么回事，app下没有libs文件夹？ 
   compile files('libs/baidumapapi_base_v4_0_0.jar')
    compile files('libs/baidumapapi_cloud_v4_0_0.jar')
    compile files('libs/baidumapapi_map_v4_0_0.jar')
    compile files('libs/baidumapapi_radar_v4_0_0.jar')
    compile files('libs/baidumapapi_search_v4_0_0.jar')
    compile files('libs/baidumapapi_util_v4_0_0.jar')

**Comment by FanYimin** [comment]
'libs 文件夹都被替代了

**Comment by Sambor123** [comment]
没有啊，你导入工程不对吧

**Comment by qq596670409** [comment]
最新更改了，原来的都没有，只需要一个jar包就可以
